<?php

/**
 * Kung Fu site curriculum page.
 *
<<<<<<< HEAD
 * @version 3/29/18
 * @author Joseph Messare
=======
 * @version 4/3/18
 * @author Ian Mackenzie
>>>>>>> iansbranch
 */

$path = './';
$page = 'Curriculum';
include $path . 'assets/inc/header.php';
?>

<h1 class="title"><?php echo $page ?></h1>

<<<<<<< HEAD
<p>
    Page content would go here.
</p>
=======
<h2>Progression</h2>
	<p>Progression in Wing Chun is denoted through various colored sashes. Moy Don will teach all the way 
	up to Master level, the gold sash. Expectations for each sash are detailed below.</p>
	
<h2>Green Sash</h2>

	<h3>FOOT AND LEG STRIKES</h3>

		<ul class="sashExpectations">
	
			<li>FRONT POKING KICK</li>
			<li>FRONT STOMPING KICK</li>
			<li>FRONT PUSH KICK</li>
			<li>ANGLE FRONT KICK</li>
			<li>SIDE KICK DEFENSIVE</li>
			<li>SIDE KICK OFFENSIVE</li>
			<li>SIDE KICK SKIPPING IN</li>
			<li>SIDE KNEE</li>
			<li>FRONT KNEE</li>
			<li>CHIN KICK FRONT</li>
			<li>CHIN KICK SIDE</li>
			<li>INSIDE FOOT SWEEP</li>
			<li>OUTSIDE FOOT SWEEP</li>
			<li>LOW TO HIGH REPEATING ANGLE FRONT KICK</li>
			<li>FRONT ANGLE TO SIDE THRUSTING KNEE KICKS</li>
	
		</ul>
 
	<h3>CLOSING DRILLS</h3>

		<ul class="sashExpectations">
	
			<li>PAK DA</li>
			<li>TAN DA</li>
			<li>LOP DA WITH CIRCLE STEP</li>
			<li>BIU JEE TO SKIP IN SIDE KICK</li>
			<li>LOW ANGLE FRONT KICK TO KNEE TO PAK DA</li>
			<li>LOW POKING KICK TO GROIN TO PAK DA</li>
			<li>LOP DA / TAN LOP DA DRILL</li>
			<li>FOCUS GLOVE DRILLS</li>
			<li>KICKING BAG DRILLS</li>
			<li>BASIC SELF DEFENSE AGAINST HAND STRIKING , COMBINATIONS, AND KICKS</li>
			<li>CHUM KIU - SEARCHING THE BRIDGE FORM AND TRANSLATIONS</li>
			<li>BEGINNING OF ROLLING AND CHANGING OF CHUNG CHI SAO - DOUBLE STICKING HANDS</li>
	
		</ul>
	
<h2>Red Sash</h2>

	<h3>CHUNG CHI SAO - ATTACKS AND DRILLS</h3>

		<ul class="sashExpectations">

			<li>PAK DA</li>
			<li>LOP DA</li>
			<li>DA OR DIM</li>
			<li>TAN DA OUTSIDE</li> 
			<li>TAN DA INSIDE</li>
			<li>SHIFTING PUNCH</li>
			<li>GARN DA</li>
			<li>GARN SAO</li>
			<li>KWAN SAU</li>
			<li>BONG SAO PRESS</li>
			<li>BIU SAO</li>
			<li>JUM SAO - DROPPING ELBOW</li>
			<li>ALL STRIKES OFF OF CHANGE</li>
			<li>PAI JARN ELBOW TRAP</li>
			<li>ALL BIU JEE FORM ATTACKS</li>
			<li>JUT DA</li>
			<li>PERFORMING ATTACK DOUBLE TOOK SAU ELBOW LIFTING ARM AND KICK</li>
			<li>PERFORMING ATTACK DOUBLE LOP DA CIRCLE STEP SWEEP</li>
			<li>TUI MA FOOTWORK</li>
			
		<ul>
		
		<ul class="sashExpectations">	
			<li>BASIC SELF DEFENSE AGAINST KNIFE ATTACKS</li>
			<li>BIU GEE - THRUSTING FINGERS OR HAND FORM AND TRANSLATION</li>
			<li>GERT JONG</li>
			<li>CHI GERT DRILLS</li>
		</ul>
		
<h2>White Sash</h2>
	
	<h3>HAND DRILLS - AGAINST HIGH STRAIGHT HANDSTRIKES</h3>
	
		<ul class="sashExpectations">
	
			<li>PAK SAU - SLAPPING HAND</li>
			<li>PAK SAU WITH SHIFT</li>
			<li>PAK DA - SLAPPING HAND WITH PUNCH</li>
			<li>TAN DA TO THE INSIDE GATE- PALM UP HAND WITH PUNCH</li>
			<li>TAN DA TO THE OUTSIDE GATE</li>
			<li>LOP DA - PULL PUNCH</li>
			<li>BONG SAU - WING UP HAND</li>
			<li>BONG / LOP DA - WING UP HAND TO PULL PUNCH</li>
			<li>BONG/ LOP DA TO TAN DA</li>
			<li>WRONG WAY BONG SAU</li>
			<li>WRONG WAY BONG SAU TO PAK DA</li>
			<li>WRONG WAY BONG SAU TO TAN DA</li>
			<li>PAK SAU / BIU SAU</li>
			<li>PAK SAU / BIU SAU TO A TAN DA ATTACK</li>
			<li>PAK SAU / BIU SAU TO A PAK DA ATTACK</li>
			
		</ul>
		
	<h3>HAND DRILLS - AGAINST HIGH OR LOW HANDS USING DOUBLE BLOCKS</h3>
	
		<ul class="sashExpectations">
		
			<li>GARN SAU- SPLITTING BLOCK HAND</li>
			<li>KWAN SAU- ROTATING POLE ARMS</li>
			<li>GARN SAU TO KWAN SAU</li>
			
		</ul>
		
	<h3>HAND DRILLS - AGAINST LOW STRIKES</h3>
		
		<ul class="sashExpectations">
		
			<li>GUM DA AGAINST THRUSTING OR STRAIGHT LOW STRIKE - PALM PUSH DOWN AND PUNCH</li>
			<li>GUM DA AGAINST A LOW UPPER CUT</li>
			<li>GARN DA INSIDE GATE - SPLITTING HAND AND PUNCH</li>
			<li>GARN DA OUTSIDE GATE</li>
			<li>DAI BONG SAU - LOW WING ARM</li>
		
		</ul>
		
	<h3>STANCES</h3>
	
		<ul class="sashExpectations">
		
			<li>YAT JI KIM YEUNG MA- GRABBING GOAT STANCE OR BASIC STANCE</li>
			<li>SIDE FACING STANCES LEFT AND RIGHT</li>
			<li>BACK HORSE STANCES LEFT AND RIGHT</li>
			
		</ul>	
			
	<h3>PUNCHING</h3>
	
		<ul class="sashExpectations">
		
			<li>YAT JI KUEN - CENTER LINE FIST</li>
			<li>SHIFTING PUNCH</li>
			<li>ADVANCING DOUBLE PUNCH OR COMBINATION PUNCHING</li>
			
		</ul>	
			
	<h3>FOOTWORK</h3>
	
		<ul class="sashExpectations">
		
			<li>PLUCKING STEPS</li>
			<li>CIRCLE STEPS</li>
			<li>SHIFTING</li>
			<li>ANGLE STEPS</li>
			
		</ul>	
		
	<ul class="sashExpectations">
	
		<li>SIL NIM TAO - LITTLE IDEA FORM - WITH ALL TRANSLATIONS OF THE FORM</li>
		<li>CHI DAN SAO - SINGLE ARM STICKING HANDS</li>
		<li>BASIC SELF DEFENSE AGAINST CONTROL MOVEMENTS, HOLDS, AND TACKLING</li>
		<li>ELBOW STRIKING UP, DOWN, AROUND, SIDE, THROUGH, BACK DRILL</li>
	
	</ul>
	
<h2>Brown Sash - Fight Level</h2>

	<p>IN ORDER TO ADVANCE PAST THIS LEVEL, ONE MUST SHOW PROFICIENCY IN FIGHTING DRILLS AND
	SPARRING AND BASIC PHYSICAL FITNESS WHICH COULD BE WAIVED FOR AGE, HEALTH, OR TRAINING ON
	YOUR OWN TIME.</p>
	
	<h3>FIGHTING DRILLS</h3>
	
		<ul class="sashExpectations">
		
			<li>REFLEX DRILLS</li>
			<li>SET SPARRING</li>
			<li>CONTINUOUS ACTION SPARRING</li>
			<li>THE TERMINATOR DRILL</li>
			<li>HAND AND BODY CONDITIONING</li>
			<li>GORE SAO AND CQB DRILLS</li>
		
		</ul>
		
	<ul class="sashExpectations">	
		
		<li>MOCK YAN JONG - WOODEN DUMMY MAN FORM AND TRANSLATION WHICH INCLUDES THE USAGE OF MOVEMENTS IN SELF DEFENSE</li>
		<li>BASIC SELF DEFENSE AGAINST GUN</li>
		
	</ul>
	
	<h3>BALANCE AND STRENGTH EXERCISES</h3>
	
		<ul class="sashExpectations">
	
			<li>PUSH UPS DIAMOND, SHOULDER WIDTH KNUCKLE, WIDE WIDTH KNUCKLE</li>
			<li>BALANCE DRILL FRONT, SIDE, BACK, FRONT</li>
			<li>BREAK FALLS</li>
			<li>SHOULDER ROLLS FRONT, BACK, SIDE</li>
			<li>SIT UPS AND CRUNCHES</li>
			<li>DEEP KNEE BENDS</li>
			<li>BAG STRIKING</li>
			<li>BEAM KICKING</li>
			
		</ul>
		
		
<h2>Black Sash - Teaching Level</h2>

	<p>THIS LEVEL IS TEACHING LEVEL. YOU MUST BE PERFECT IN EXPLAINING ALL OF THE SYSTEMS UP TO THIS POINT. 
	PEOPLE PASSING THIS LEVEL ARE CONSIDERED SIFU OR TEACHERS OF THE SYSTEM AND
	CAN RUN CLASSES OR A SCHOOL UNDER A MASTER'S NAME AND GUIDANCE.</p>
	
	<ul class="sashExpectations">
	
		<li>LUK DIM BOON KWAN - 6 1/2 POINT POLE FORM AND TRANSLATION</li>
		<li>USAGE OF POLE IN COMBATIVE TECHNIQUES</li>
		<li>CHI KWAN OR STICKING POLE</li>
		<li>TEACHING CLASSES IN SCHOOL AND GRADED IN HOW YOU CAN EXPLAIN SYSTEM</li>
		<li>BASIC SELF DEFENSE AGAINST CLUB AND BAT</li>
		<li>PROFICIENCY IN COMPLETE SYSTEM TEACHING AND USAGE UNTIL THIS POINT</li>
	
	</ul>
	
<h2>Gold Sash - Master Level</h2>

	<h3>MASTERED ALL SYSTEMS, INCLUDING FIGHTING ABILITIES. THIS INCLUDES THE FOLLOWING REQUIREMENTS:</h3>
	
		<ul class="sashExpectations">
		
			<li>BAAT JAAM DO - EIGHT WAY SLASHING/ CUTTING KNIVES OR SWORDS - FORM AND USAGE IN FIGHTING
			BASIC SELF DEFENSE AGAINST ADVANCED WEAPONRY SUCH AS SWINGING WEAPONS AND DISTANCE</li>
			
			<li>WEAPONS, INCLUDING DUAL WEAPONS USED IN PAIRS</li>
			
			<li>CONTINUOUS SPARRING AGAINST MULTIPLE OPPONENTS ONE AFTER ANOTHER OR CIRCLE OF IRON</li>
			
			<li>DRILL AND ONSLAUGHT DRILLS</li>
			
			<li>A FULL WEEKEND OF TESTING OF ALL TYPES OF MENTAL, ORAL, WRITTEN, PHYSICAL, AND SPIRITUAL CHALLENGES</li>
			
			<li>YOU WILL FULLY UNDERSTAND BOTH THE INTERNAL AND EXTERNAL NATURE OF VING TSUN (WING CHUN)</li>
			
			<li>PERFECT KNOWLEDGE OF THE ART, ITS ORIGIN, HISTORY, LINEAGE, EXPLANATION, AND UTILIZATION OF
			ALL TECHNIQUES.</li>
			
			<li>PERFECT MASTERY OF YOURSELF AND THE ART</li>
			
			<li>ONE MUST SHOW DISCIPLINE , HUMILITY, CONFIDENCE, COMPASSION, CONTROL, AND HUMANITY</li>
			
		</ul>
		
		<p>ADVANCED PHYSICAL FITNESS FOR THOSE UNDER FORTY OR THOSE ABLE TO BY A DOCTORS RELEASE
		JOIN WHO IS OVER FORTY. THIS INCLUDES LONG DISTANCE RUNNING, MANY DIFFERENT SPRINTS,
		SPARRING, DRILLS, EXERCISES AND ALL UNDER DURESS AND HIGH STRESS INCLUDING A GAUNTLET
		THAT WILL TEST YOUR ABILITY TO HANDLE HIGH STRESS SITUATIONS, DEFENSE AGAINST ALL WEAPONS
		AND HAND TO HAND SCENARIOS, FIGHTING OFF MULTIPLE ATTACKERS ETC... ETC A WEEKEND OF PURE
		HELL. THOSE WHO PASS WILL BE PROUD TO BE CALLED A MASTER AND HUMBLE ENOUGH TO JUST BE
		CALLED TEACHER (SIFU) AND UNDERSTAND WHY.</p>
			
>>>>>>> iansbranch
</body>
</html>